### ISSUE TITLE
Option to disable live updates for live feed

### ISSUE THREAD

**Issue by andersme** [Afischbacher/Nhl.Api#23] opened 2021-12-18 00:23 UTC
I like that there is the live updating on the LiveGameFeedResult class, but this should at least be configurable to turn off, or slow down. I have certain use cases where I'm pulling in the live feed to download shot data and I don't need live updating. I do have another case where the live updating is nice, but 250ms is way too fast. If this could be fixed ASAP, that would be excellent.

**Comment by andersme** [comment] 2021-12-18 00:40
It also appears that the task inside that object is not disposed and goes on forever.

**Comment by Afischbacher** [comment] 2021-12-18 16:39
Hey @andersme,

Yes! This is something I definitely wanted to implement in future versions, so it's something I can put in 1.7.0.

As for the `Task.Run` inside the constructor of the `LiveGameFeed`  that runs `RaiseOnLiveGameFeedChangeEvent` the while loop does exit based on to many conditions such as game state and number of attempts. And for disposal of `Task.Run`, see here https://devblogs.microsoft.com/pfxteam/do-i-need-to-dispose-of-tasks/ 

My goal is to get this release out as soon as possible, sorry for the wait!

Thanks @andersme for all your hard work and suggestions they have been great!

**Comment by andersme** [comment] 2021-12-18 18:20
We've just noticed that when get a feed for a given game in our Blazor app, that task continues on forever. If we navigate back and forth to the page, more and more of those tasks are running until the app runs out of memory or kills our internet. There needs to be some way to cancel the task when disposing the feed object or something to that effect. I think this live updating being opt-in only would be a good start.

**Comment by Afischbacher** [comment] 2021-12-18 19:06
Ah I see your point from that perspective, I see the issue, every time you navigate you to the page in your Blazor web application, it requests a new instance of the Live Game Feed Result, the problem is the number of attempts is quite long and is causing tasks to run for a long period of time, and as you refresh the page, the tasks keep getting spun up and persisted for a long period of time.

**Comment by Afischbacher** [comment] 2021-12-19 04:39
https://github.com/Afischbacher/Nhl.Api/pull/24

**Comment by Afischbacher** [comment] 2021-12-21 17:52
Released v1.70! So I will close this issue :) 👍

**Closed by Afischbacher** 2021-12-21 17:52 UTC
